services:
  kanban-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: angular-kanban
    restart: unless-stopped
    networks:
      - kanban-network

networks:
  kanban-network:
    driver: bridge